apiVersion: batch/v1
kind: Job
metadata:
  name: autoresume-generate-pdf
  namespace: autoresume
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: autoresume
          image: ghcr.io/ngozikanwachukwu/autoresume:main
          imagePullPolicy: Always
          workingDir: /app
          command:
            - python
            - -m
            - src.cli
            - --input
            - /in/minimal.json
            - --output
            - /out/AutoResume.pdf
          volumeMounts:
            # Read-only input JSON from ConfigMap
            - name: input
              mountPath: /in
              readOnly: true
            # Writable scratch space for the generated PDF
            - name: output
              mountPath: /out
      volumes:
        - name: input
          configMap:
            name: autoresume-sample
            items:
              - key: minimal.json
                path: minimal.json
        - name: output
          emptyDir: {}
