name: docker

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Enable cross-arch builds (needed for main when we build arm64 too)
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        run: echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      # 👇 Build only amd64 on PRs (fast), build amd64+arm64 on main (multi-arch)
      - name: Decide platforms
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "PLATFORMS=linux/amd64,linux/arm64" >> $GITHUB_ENV
          else
            echo "PLATFORMS=linux/amd64" >> $GITHUB_ENV
          fi

      - name: Build (PR) / Build+Push (main) runtime image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.runtime
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          platforms: ${{ env.PLATFORMS }}
          tags: |
            ghcr.io/${{ env.OWNER }}/autoresume:${{ github.sha }}
            ghcr.io/${{ env.OWNER }}/autoresume:main
          cache-from: type=gha
          cache-to: type=gha,mode=max
