name: docker

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # trying to make owner lowercase so tags are valid for GHCR... hopefully this works
      - name: Set lowercase owner
        run: echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build (PR) / Build+Push (main) runtime image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.runtime
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ env.OWNER }}/autoresume:${{ github.sha }}
            ghcr.io/${{ env.OWNER }}/autoresume:main
          cache-from: type=gha
          cache-to: type=gha,mode=max
